// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe/internal/logic/admin"
	_ "goframe/internal/logic/file"
	_ "goframe/internal/logic/login"
)
