// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Config is the golang structure of table jin_config for DAO operations like Where/Data.
type Config struct {
	g.Meta     `orm:"table:jin_config, do:true"`
	Id         interface{} //
	Name       interface{} // 配置名
	Value      interface{} // 配置内容
	Type       interface{} // 配置类型 0后台 1会员小程序
	Remark     interface{} //
	CreateTime interface{} //
	UpdateTime interface{} //
}
