// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// JinUser is the golang structure of table jin_user for DAO operations like Where/Data.
type JinUser struct {
	g.Meta     `orm:"table:jin_user, do:true"`
	Id         interface{} //
	Nickname   interface{} // 昵称
	HeadImage  interface{} // 头像
	Sex        interface{} // 性别,1男，2女，0未知
	Phone      interface{} // 手机
	Birthday   interface{} // 出生年月日 日期
	MinaOpenid interface{} // 会员小程序openid
	Unionid    interface{} // 主体下微信用户唯一标示
	LevelId    interface{} // 会员等级id
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
}
