// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserDao is the data access object for table jin_user.
type UserDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns UserColumns // columns contains all the column names of Table for convenient usage.
}

// UserColumns defines and stores column names for table jin_user.
type UserColumns struct {
	Id         string //
	Nickname   string // 昵称
	HeadImage  string // 头像
	Sex        string // 性别,1男，2女，0未知
	Phone      string // 手机
	Birthday   string // 出生年月日 日期
	MinaOpenid string // 会员小程序openid
	Unionid    string // 主体下微信用户唯一标示
	LevelId    string // 会员等级id
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
}

//  userColumns holds the columns for table jin_user.
var userColumns = UserColumns{
	Id:         "id",
	Nickname:   "nickname",
	HeadImage:  "head_image",
	Sex:        "sex",
	Phone:      "phone",
	Birthday:   "birthday",
	MinaOpenid: "mina_openid",
	Unionid:    "unionid",
	LevelId:    "level_id",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// NewUserDao creates and returns a new DAO object for table data access.
func NewUserDao() *UserDao {
	return &UserDao{
		group:   "default",
		table:   "jin_user",
		columns: userColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserDao) Columns() UserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
