// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	apiAdmin "goframe/api/v1/admin"
)

type IFile interface {
	UploadLocal(ctx context.Context, req *apiAdmin.UploadFileReq) (res *apiAdmin.UploadFileRes, err error)
	UploadOss(ctx context.Context, req *apiAdmin.UploadFileReq) (res *apiAdmin.UploadFileRes, err error)
}

var localFile IFile

func File() IFile {
	if localFile == nil {
		panic("implement not found for interface IFile, forgot register?")
	}
	return localFile
}

func RegisterFile(i IFile) {
	localFile = i
}
