// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	apiAdmin "goframe/api/v1/admin"
)

type ILogin interface {
	Sign(ctx context.Context, req *apiAdmin.LoginReq) (res *apiAdmin.LoginRes, err error)
	Logout(ctx context.Context, req *apiAdmin.LoginLogoutReq) (res *apiAdmin.LoginLogoutRes, err error)
}

var localLogin ILogin

func Login() ILogin {
	if localLogin == nil {
		panic("implement not found for interface ILogin, forgot register?")
	}
	return localLogin
}

func RegisterLogin(i ILogin) {
	localLogin = i
}
