// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// JinConfig is the golang structure for table jin_config.
type JinConfig struct {
	Id         uint64 `json:"id"         ` //
	Name       string `json:"name"       ` // 配置名
	Value      string `json:"value"      ` // 配置内容
	Type       int    `json:"type"       ` // 配置类型 0后台 1会员小程序
	Remark     string `json:"remark"     ` //
	CreateTime uint   `json:"createTime" ` //
	UpdateTime uint   `json:"updateTime" ` //
}
