// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id         uint64 `json:"id"         ` //
	Nickname   string `json:"nickname"   ` // 昵称
	HeadImage  string `json:"headImage"  ` // 头像
	Sex        int    `json:"sex"        ` // 性别,1男，2女，0未知
	Phone      string `json:"phone"      ` // 手机
	Birthday   string `json:"birthday"   ` // 出生年月日 日期
	MinaOpenid string `json:"minaOpenid" ` // 会员小程序openid
	Unionid    string `json:"unionid"    ` // 主体下微信用户唯一标示
	LevelId    int    `json:"levelId"    ` // 会员等级id
	CreateTime int    `json:"createTime" ` // 创建时间
	UpdateTime int    `json:"updateTime" ` // 更新时间
}
